# Generated by Django 5.1.2 on 2024-11-02 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liblle', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comptes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liblle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Chambres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='image_chambre')),
                ('prix', models.IntegerField()),
                ('id_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionhotel.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('num_compte', models.IntegerField()),
                ('durer', models.IntegerField()),
                ('code_reservation', models.IntegerField(unique=True)),
                ('chambre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestionhotel.chambres')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionhotel.comptes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
