# Generated by Django 5.1.2 on 2024-11-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionhotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.TextField(max_length=60)),
                ('nom', models.CharField(max_length=60)),
                ('postnom', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
